
export const adjectives = [
    "Law",
    "Righteous",
    "Trial",
    "Iron",
    "Courtroom",
    "Justice",
    "Mighty",
    "Litigant's",
    "Steel",
    "Plaintiff's",
    "Damages",
    "Lawful",
    "Money",
    "Cash",
    "Honest",
    "Legal",
    "Combative",
    "Strong",
    "Zealous",
    "Rabid",
    "Courthouse",
    "Judgement",
    "Tribunal",
    "Court",
    "Tribunal",
    "Judgment",
    "Settlement",
    "Payout",
]

export const nouns = [
    "Hammer",
    "Cobra",
    "Tiger",
    "Eagle",
    "Cowboy",
    "Arm",
    "Knight",
    "Armadillo",
    "Grizzly",
    "Advocate",
    "Rattlesnake",
    "Locomotive",
    "Lion",
    "Croc",
    "Badger",
    "Hornet",
    "Bulldog",
    "Shark",
    "Fist",
    "Champ",
    "Conqueror",
    "Viking",
    "Hero",
    "Blade",
    "Lord",
    "Advocate",
    "Panther",
]

export const monthsOptions = [
    { label: "January", value: 1},
    { label: "February", value: 2},
    { label: "March", value: 3},
    { label: "April", value: 4},
    { label: "May", value: 5},
    { label: "June", value: 6},
    { label: "July", value: 7},
    { label: "August", value: 8},
    { label: "September", value: 9},
    { label: "October", value: 10},
    { label: "November", value: 11},
    { label: "December", value: 12},
]